# Generated by Django 5.2.1 on 2025-06-08 19:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_phone_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday')], max_length=20)),
                ('exercise', models.CharField(max_length=255)),
                ('sets', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('repetition', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Exercise',
            },
        ),
    ]
