# Generated by Django 5.2.1 on 2025-06-12 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_order_order_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='track_code',
            field=models.CharField(default='ORD-TI0EWD4N-2025061251', editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
