# Generated by Django 5.2.1 on 2025-06-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField()),
                ('uploaded_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
